#!/usr/bin/env bash

#=============================================================================
# MY ALIASES
#=============================================================================

# alias findsz="find . -maxdepth ${1:-1} -type d -exec du -sh {} + | sort -h"
# alias findsz="find . -maxdepth 2 -type d -exec du -sh {} + | sort -h"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
# alias cleanvenvdir="find . -type d -name '*.venv' -exec rm -rf {} +"

alias runsshagent='eval $(ssh-agent)'
#=============================================================================

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd ..&& ls -1"
alias ...="cd ../.. && ls -1"
alias ....="cd ../../.. && ls -1"
alias .....="cd ../../../.. && ls -1"
alias -- -="cd -" # `-` is the name of the new shortcut you are creating. `--` is the "End of Options" flag. It tells the alias command, "The next character is part of the name I want to create, not a configuration flag". Without this, the shell would think the `-` is a mistake.


alias dl="cd $HOME/Downloads && ls -1"
alias dt="cd $HOME/Desktop && ls -1"
alias doc="cd $HOME/Documents && ls -1"
alias ss="open $HOME/Desktop/ss"
alias mdstyle="code $HOME/.local/state/crossnote/style.less"

alias bu="code $DOTFILES/bash_utils.bash"
alias secrets="code $DOTFILES/secrets.bash"
alias aliases="code $DOTFILES/aliases"
alias galiases="code $DOTFILES/git-aliases.bash"
alias sshconfig="code $HOME/.ssh/config"
alias chrome="open -na 'Google Chrome' --args --new-window" # open new (`-n`) Chrome application (`-a`) with arguments (`--args` and `--new-window`)
alias chromeincog="open -na 'Google Chrome' --args --new-window --incognito" # open new (`-n`) Chrome application (`-a`) with arguments (`--args` and `--new-window`)
alias ae="deactivate &> /dev/null; source .venv/bin/activate"
alias de="deactivate"
alias pae="pyenv activate $1"
alias pde="pyenv deactivate"
# alias uae="source $UV/$1/bin/activate"
uae() {
    source "$UV/$1/bin/activate" && echo -e "Activated \033[0;32m$1\033[0m Virual Environment, which is located in $UV"
}
alias ude="pyenv deactivate"
alias cae="conda activate $1"
alias cde="conda deactivate"


alias jlb="jupyter-lab"
alias jnb="jupyter notebook"

# =============================================================================
# =============================================================================

alias ntpdf="open $NTBS/nts && open $NTBS/PDFs"
alias ntbs="cd $NTBS"
alias ntabc="code $NTBS/nts/notes_arabic.md"
alias ntshell="code $NTBS/nts/notes_shell.md"
alias ntbash="code $NTBS/nts/notes_bash.md"
alias ntlnx="code $NTBS/nts/notes_linux.md"
alias ntgql="code $NTBS/nts/notes_graphql.md"
alias ntdb="code $NTBS/nts/notes_db.md"
alias ntwaf="code $NTBS/nts/notes_waf.md"
alias ntde="code $NTBS/nts/notes_data_engineering.md"
alias ntgcp="code $NTBS/nts/notes_gcp.md"
alias ntemail="code $NTBS/interviewprep/email_analysis.md"
alias ntfw="code $NTBS/nts/notes_fw.md"
alias ntmd="code $NTBS/nts/notes_md.md"
alias ntawscli="code $NTBS/nts/notes_aws_cli.md"
alias ntaws0="code $NTBS/nts/notes_aws0.md"
alias ntaws1="code $NTBS/nts/notes_aws1.md"
alias ntaws2="code $NTBS/nts/notes_aws2.md"
alias ntdjango="code $NTBS/nts/notes_django.md"
alias ntre="code $NTBS/nts/notes_re.md"
alias ntml="code $NTBS/nts/notes_ml.md"
alias ntnsql="code $NTBS/nts/notes_nosql.md"
alias ntkafka="code $NTBS/nts/notes_kafka.md"
alias ntyml="code $NTBS/nts/notes_yml.md"
alias ntgit="code $NTBS/nts/notes_git.md"
alias ntdkr="code $NTBS/nts/notes_docker.md"
alias ntaf="code $NTBS/nts/notes_airflow.md"
alias ntvim="code $NTBS/nts/notes_vim.md"
alias ntvsc="code $NTBS/nts/notes_vscode.md"
alias ntmac="code $NTBS/nts/notes_mac.md"
alias ntpy="code $NTBS/nts/notes_python.md"
alias ntpytl="code $NTBS/nts/notes_pytools.md"
alias ntdvtl="code $NTBS/nts/notes_devtools.md"
alias ntpytest="code $NTBS/nts/notes_pytest.md"
alias nteng="open /Users/a.momin/gd/Writing\ English/Notes_English.gsheet"
alias ntflask="code $NTBS/nts/notes_flask.md"
alias ntfastapi="code $NTBS/nts/notes_fastapi.md"
alias ntjira="code $NTBS/nts/notes_jira.md"
alias ntcss="open $NTBS/nts/notes_css.gdoc"
alias nthtml="open $NTBS/nts/notes_html.gdoc"
alias ntjnb="code $NTBS/nts/notes_jnb.md"
alias ntfintech="code $NTBS/nts/notes_fintech.md"
alias ntcicd="code $NTBS/nts/notes_cicd.md"
alias ntnw="code $NTBS/nts/notes_networking.md"
alias nttableau="code $NTBS/nts/notes_tableau.md"
alias ntstat="code $NTBS/nts/notes_statistics.md"
alias ntspark="code $NTBS/nts/notes_spark.md"
alias ntopenai="code $NTBS/nts/notes_openai.md"
alias ntoop="code $NTBS/nts/notes_oop.md"
alias ntcelery="code $NTBS/nts/notes_celery.md"
alias ntdrf="code $NTBS/nts/notes_drf.md"
alias ntwaf="code $NTBS/nts/notes_waf.md"
alias ntds="code $NTBS/nts/notes_ds.md"
alias nttf="code $NTBS/nts/notes_terraform.md"
alias ntansible="code $NTBS/nts/notes_ansible.md"
alias ntopenssl="code $NTBS/nts/notes_openssl.md"
alias ntselenium="code $NTBS/nts/notes_selenium.md"
alias ntbehave="code $NTBS/nts/notes_behave.md"
alias ntxpath="code $NTBS/nts/notes_xpath.md"
alias ntawsglue="code $NTBS/nts/notes_awsglue.md"
alias ntprompt="code $NTBS/nts/notes_prompts.md"
alias ntllm="code $NTBS/nts/notes_llm.md"
alias ntdatabricks="code $NTBS/nts/notes_databricks.md"
alias ntcb="code $NTBS/nts/notes_cybersecurity.md"
alias ntdos="code $NTBS/nts/notes_windows.md"

alias ntcolabtl="code $NTBS/nts/notes_colaboration_tools.md"
alias ntwbapi="code $NTBS/nts/notes_web_api.md"
alias ntsysdgn="code $NTBS/nts/notes_system_designs.md"
alias ntserverless="code $NTBS/nts/notes_serverless.md"

###############################################################################
alias ntcarlog="code $NTBS/nts/notes_car_log.md"
alias ntislam="code $NTBS/nts/notes_islam.md"
alias nteng="code $NTBS/eng/notes_english.md"
alias nttmp="code $NTBS/nts/notes_tmp.md"
###############################################################################
alias cmdnpm="code $NTBS/nts/cmd_npm.txt"
alias cmdreact="code $NTBS/nts/cmd_react.txt"
alias cmdcpp="code $NTBS/nts/cmd_cpp.txt"
alias cmdspark="code $NTBS/cmds/cmd_pyspark.md"
alias cmdawsglue="code $NTBS/cmds/cmd_awsglue.md"
###############################################################################

## INTERVIEW QUESTIONS
alias iqmicroservice="code $NTBS/iqs/iq_microservice.md"
alias iqsysdgn="code $NTBS/iqs/iq_system_designs.md"
alias ivsupport="code $NTBS/interviewprep/interview_support.md"
alias iq="code $NTBS/iqs/iq_questions.md"
alias iqs="code $NTBS/iqs"
alias iqaws="code $NTBS/iqs/iq_aws.md"
alias iqspark="code $NTBS/iqs/iq_spark.md"
alias iqpython="code $NTBS/iqs/iq_python.md"
alias iqdjango="code $NTBS/iqs/iq_django.md"
alias iqdrf="code $NTBS/iqs/iq_drf.md"
alias iqdb="code $NTBS/iqs/iq_db.md"
alias iqsql="code $NTBS/iqs/iq_sql.md"
# =============================================================================

## JUPYTER NOTEBOOKS
alias nbsql="code $NTBS/nbs/nt_sql.ipynb"
alias nbsqliq="code $SD/Databases/RDBMS/sql/notebooks/sql_queries_questions.ipynb"
alias nbsqllc="code $SD/Databases/RDBMS/sql/notebooks/leetcode_sql_questions.ipynb"
alias nbepp="code $NTBS/nbs/nt_epp.ipynb"
alias nbpypkg="code $NTBS/nbs/nt_python_packages.ipynb"
alias nboop="code $NTBS/nbs/nt_oop.ipynb"
alias nbpd="code $NTBS/nbs/nt_pd.ipynb"
alias nbspark="code $NTBS/nbs/nt_spark.ipynb"
alias nbsparksql="code $NTBS/nbs/nt_spark_sql.ipynb"
alias nbnp="code $NTBS/nbs/nt_np.ipynb"
alias nbplt="code $NTBS/nbs/nt_plt.ipynb"
alias nbml="code $NTBS/nbs/nt_ml.ipynb"
alias nbtorch="code $NTBS/nbs/nt_torch.ipynb"
alias nbstat="code $NTBS/nbs/statistics.ipynb"
alias nbadhocsql="code $NTBS/nbs/adhoc_sql.ipynb"
# =============================================================================

dkr_aliases(){
    #========== Docker Shortcuts =============
    image_tag=$1
    container_info=$(docker ps | grep $image_tag)

    alias dps="docker ps | grep ${container_info:0:12}"
    alias dstp="docker stop ${container_info:0:12}"
    alias dbld="""docker build -t "${image_tag}""""
    alias dlg="docker logs --follow ${container_info:0:12}"
    alias dx="docker exec -it ${container_info:0:12} bash"
}

pvt_aliases(){

    alias bp="code $DOTFILES/bash_profile_mos01" # bp ==> Bash Profile
    alias startmysql="sudo /usr/local/mysql/support-files/mysql.server start"
    alias stopmysql="sudo /usr/local/mysql/support-files/mysql.server stop"
    alias statusmysql="sudo /usr/local/mysql/support-files/mysql.server status"
    alias logmysql="sudo tail -f /usr/local/mysql/data/$(hostname).err"
    alias mvpdf="mv $NTBS/{nts,cmds}/*.pdf $GD/NOTES_PDF/notes/"

    alias adhocsql="code $SD/Databases/RDBMS/sql/schemas/adhocsql.sql"
    alias adhocspark="code $SD/Big_Data/elements_of_spark/adhocspark.py"

    # NON-TECHNICAL
    alias passdb="open $HOME/mydocs/gd/passdb.gsheet"
    alias jobdb="open $HOME/mydocs/gd/jobs/Jobs_DB.gsheet"
    alias apartments="code $GD/MISC/apartments.md"
    alias ntrgh="code $HOME/notes_rough.md"
    alias ntht="code $HOME/mydocs/gd/Harness-Tech/notes_ht.md"


    alias mlcourses="cd $HOME/mydocs/Software_Development/Machine_Learning/ml_courses && ls -1"
    alias ml="cd $HOME/mydocs/Software_Development/Machine_Learning && ls -1"                 # ml ==> Machine_Learning
    alias bigdata="cd $HOME/mydocs/Software_Development/Big_Data"
    alias deds="cd $HOME/mydocs/Software_Development/DEDS && ls -1"                     # deds ==> Data_Engineering_Data_Science
    alias books="cd $HOME/mydocs/BOOKS/PDF\ Books && ls -1"
    alias llmapp="cd $SD/llm_app && ls -1"
    alias ads="cd $HOME/mydocs/Software_Development/Algorithms_and_Data_Structures"
    alias epi="cd $HOME/mydocs/Software_Development/Python_Program/Python3/elements-of-programming-interview && deactivate &> /dev/null; source .venv/bin/activate"
    alias pp="cd $HOME/mydocs/Software_Development/Python_Program && ls -1"                   # pp ==> Python Program
    alias pp2="cd $HOME/mydocs/Software_Development/Python_Program/Python2 && ls -1"          # pp2 ==> Python2 Program
    alias pp3="cd $HOME/mydocs/Software_Development/Python_Program/Python3 && ls -1"          # pp3 ==> Python3 Program
    alias jp="cd $HOME/mydocs/Software_Development/JavaPragrams && ls -1"                     # cpp ==> C++ Programs
    alias jsp="cd $HOME/mydocs/Software_Development/Web_Development/Javascript_Program && ls -1"                         # pp3 ==> Python3 Program
    alias cpp="cd $HOME/mydocs/Software_Development/C++_Programs && ls -1"                    # cpp ==> C++ Programs
    alias algs4="cd $HOME/mydocs/Software_Development/algs4/src/main/java/edu/princeton/cs/algs4"
    alias db="cd $HOME/mydocs/Software_Development/Databases && ls -1"                        # sql ==> MySQL Program
    alias nttax="code $GD/TaxReturn/notes_tax.md"

    alias mydocs="cd $HOME/mydocs && ls -1"
    alias gd="cd $HOME/mydocs/gd && ls -1"
    alias sd="cd $HOME/mydocs/Software_Development && ls -1"
    alias wd="cd $HOME/mydocs/Software_Development/Web_Development && ls -1"
    alias resumes="open $GD/jobs/resumes"
    alias curresume="open $GD/jobs/resumes/AM-DE-PYDEV.gdoc"
    alias myresume="open $GD/jobs/resumes/AM-DE-PYDEV.gdoc"
    alias resumede="open $GD/jobs/resumes/AM-DE.gdoc"
    alias mvntpdf="mv $NTBS/{nts,iqs}/*.pdf $GD/NOTES_PDF/notes/"

    alias python=python3
    alias pip=pip3
    alias vim=nvim

    # alias tmux="tmux 2"

    # Rough or Tmp Aliases
    alias ntbh="code $NTBS/nts/notes_buy_houses.md"
}

c1_aliases(){

    alias dt="cd $DT"
    alias dl="cd $DL"
    alias gd='cd "$GD" && ls -1'
    alias doc='cd "$DOC" && ls -1'
    alias cb="cd $CODEBASE"
    alias ntBSc1='cd "$NTBSC1" && ls -1'

    #========== C1 Shortcuts =============
    alias ntrgh='code "$HOME"/notes_rough.md'
    alias ntrgh2='code "$NTBSC1"/notes_rough2.md'
    alias ntc1='code "$NTBSC1"/notes_c1.md'
    alias ntdoc='code "$NTBSC1"/ntdoc.md'
    alias ntdsu='code "$NTBSC1"/ntdsu.md'
    alias nttkt='code "$NTBSC1"/nttkt.md'

    alias buc1='code "$NTBSC1"/.utils/bash_utils_c1.sh'
    alias nbadhocsh='code "$NTBSC1"/bscripts_jnb/adhocsh.ipynb'

}
