SELECT *
FROM Student;

SELECT *
FROM Enrollment;

SELECT *
FROM Course;

SELECT S.*, C.*
FROM STUDENT S
INNER JOIN ENROLLMENT E ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C ON E.COURSE_ID = C.COURSE_ID;


SELECT *
FROM Student
INNER JOIN Enrollment ON Student.STUDENT_ID = Enrollment.STUDENT_ID
INNER JOIN Course ON Enrollment.COURSE_ID = Course.COURSE_ID;