SELECT * FROM EMPLOYEE;

SELECT E1.*
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.EMPLOYEE_ID = E2.MANAGER_ID;

SHOW INDEX FROM Employee;

-- Create the view without parentheses
DROP VIEW IF EXISTS EMP_BNS;

CREATE VIEW EMP_BNS AS (SELECT EMPLOYEE_REF_ID FROM BONUS GROUP BY EMPLOYEE_REF_ID);

-- Use the view in a query

SELECT * FROM EMP_BNS;

SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE_ID IN ( SELECT EMPLOYEE_REF_ID FROM EMP_BNS);

SELECT * FROM BONUS;